# Generated by Django 5.1.7 on 2025-09-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("experience", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
